[package]
name = "reflink-split"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
byte-unit = "5.1"
env_logger = "0.11"
itoa = "1.0"
log = "0.4"
nix = { version = "0.29", features = ["zerocopy"] }
